# Generated by Django 4.0.1 on 2022-02-10 16:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IIIFResource',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.URLField(unique=True, verbose_name='IIIF id')),
                ('iiif_type', models.CharField(max_length=30)),
                ('label', models.JSONField(blank=True, null=True)),
                ('thumbnail', models.JSONField(blank=True, null=True)),
                ('iiif_json', models.JSONField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['original_id'], name='iiif_store__origina_680c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['iiif_type'], name='iiif_store__iiif_ty_b8f055_idx'),
        ),
        migrations.AddIndex(
            model_name='iiifresource',
            index=models.Index(fields=['label'], name='iiif_store__label_ebdfe9_idx'),
        ),
    ]
