# Generated by Django 3.1.6 on 2021-03-31 14:42

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredIIIFResource",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_id", models.URLField(verbose_name="IIIF id")),
                ("iiif_type", models.CharField(max_length=30)),
                ("label", models.JSONField(blank=True, null=True)),
                ("thumbnail", models.JSONField(blank=True, null=True)),
                ("iiif_json", models.JSONField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
